import type { ThinkingEffortTier } from './compare-reference';
import type { CanonicalModel, CapabilityKey, CapabilityScore, ModelLifecycle, ProviderId } from '../types';

function score(value: number, source: CapabilityScore['source'] = 'inferred'): CapabilityScore {
  return { value, source };
}

function thinkingMeta(input: {
  tiers: ThinkingEffortTier[];
  defaultTier: ThinkingEffortTier;
  parameter: string;
  notes?: string;
  baseline?: boolean;
}): CanonicalModel['metadata'] {
  return {
    compareUpdated: '2026-09-01',
    ...(input.baseline ? { platformBaseline: true } : {}),
    thinkingEffort: {
      parameter: input.parameter,
      tiers: input.tiers,
      defaultTier: input.defaultTier,
      ...(input.notes ? { notes: input.notes } : {}),
    },
  };
}

function caps(flags: Partial<CanonicalModel['capabilities']> & { scores?: Partial<Record<CapabilityKey, CapabilityScore>> }): CanonicalModel['capabilities'] {
  return {
    reasoning: Boolean(flags.reasoning),
    coding: Boolean(flags.coding),
    agents: Boolean(flags.agents),
    tools: Boolean(flags.tools ?? flags.agents),
    vision: Boolean(flags.vision),
    audio: Boolean(flags.audio),
    embeddings: Boolean(flags.embeddings),
    structured_output: Boolean(flags.structured_output ?? true),
    streaming: flags.streaming !== false,
    batch: Boolean(flags.batch),
    multimodal: Boolean(flags.multimodal ?? flags.vision),
    scores: flags.scores || {},
  };
}

function model(input: Omit<CanonicalModel, 'status' | 'discoveredAt' | 'updatedAt' | 'metadata' | 'regionSupport' | 'complianceTags' | 'modelOwner'> & Partial<CanonicalModel>): CanonicalModel {
  return {
    ...input,
    status: input.status || 'active',
    discoveredAt: input.discoveredAt ?? null,
    updatedAt: input.updatedAt ?? null,
    metadata: input.metadata || {},
    regionSupport: input.regionSupport || ['global'],
    complianceTags: input.complianceTags || [],
    modelOwner: input.modelOwner ?? input.providerId,
  };
}

const seed: CanonicalModel[] = [
  model({
    id: 'openai:gpt-5.6-sol',
    providerId: 'openai',
    providerModelId: 'gpt-5.6-sol',
    displayName: 'GPT-5.6 Sol',
    family: 'gpt-5.6',
    version: '5.6',
    aliases: ['gpt-5.6-sol', 'best_reasoning', 'best'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-08-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 1_050_000,
    maxOutputTokens: 128_000,
    latencyProfile: 'balanced',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true, vision: true, structured_output: true, multimodal: true,
      scores: { reasoning: score(10), coding: score(10), agentic: score(10) },
    }),
    pricing: { inputPerMillionUsd: 4, outputPerMillionUsd: 20, currency: 'USD', source: 'provider_declared' },
    metadata: thinkingMeta({
      parameter: 'reasoning.effort',
      tiers: ['low', 'medium', 'high', 'extrahigh', 'ultra'],
      defaultTier: 'medium',
      baseline: true,
      notes: 'API also supports none and max. Ultra is a ChatGPT Work / Codex parallel-agent mode, not an API effort slug.',
    }),
  }),
  model({
    id: 'openai:gpt-5.6-terra',
    providerId: 'openai',
    providerModelId: 'gpt-5.6-terra',
    displayName: 'GPT-5.6 Terra',
    family: 'gpt-5.6',
    version: '5.6',
    aliases: ['gpt-5.6-terra', 'best_agent'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-08-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 1_050_000,
    maxOutputTokens: 64_000,
    latencyProfile: 'balanced',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true, vision: true, multimodal: true,
      scores: { reasoning: score(9), coding: score(9), agentic: score(10) },
    }),
    pricing: { inputPerMillionUsd: 2, outputPerMillionUsd: 12, currency: 'USD', source: 'provider_declared' },
    metadata: thinkingMeta({
      parameter: 'reasoning.effort',
      tiers: ['low', 'medium', 'high', 'extrahigh'],
      defaultTier: 'medium',
      notes: 'Strong agentic default when Sol latency or cost is too high.',
    }),
  }),
  model({
    id: 'openai:gpt-5.6-luna',
    providerId: 'openai',
    providerModelId: 'gpt-5.6-luna',
    displayName: 'GPT-5.6 Luna',
    family: 'gpt-5.6',
    version: '5.6',
    aliases: ['gpt-5.6-luna', 'best_fast'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-08-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 256_000,
    maxOutputTokens: 32_000,
    latencyProfile: 'fast',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true,
      scores: { reasoning: score(7), coding: score(8) },
    }),
    pricing: { inputPerMillionUsd: 0.2, outputPerMillionUsd: 1.2, currency: 'USD', source: 'provider_declared' },
    metadata: thinkingMeta({
      parameter: 'reasoning.effort',
      tiers: ['low', 'medium', 'high', 'extrahigh'],
      defaultTier: 'medium',
      notes: 'Best fit for high-volume classification and UI customization drafts.',
    }),
  }),
  model({
    id: 'openai:gpt-5.4-mini',
    providerId: 'openai',
    providerModelId: 'gpt-5.4-mini',
    displayName: 'GPT-5.4 Mini',
    family: 'gpt-5.4',
    version: '5.4',
    aliases: ['gpt-5.4-mini', 'best_cost'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-04-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 128_000,
    maxOutputTokens: 16_000,
    latencyProfile: 'fast',
    capabilities: caps({ reasoning: true, coding: true, tools: true, scores: { reasoning: score(6), coding: score(7) } }),
    pricing: { inputPerMillionUsd: 0.15, outputPerMillionUsd: 0.6, currency: 'USD', source: 'inferred' },
  }),
  model({
    id: 'openai:gpt-5.3-codex',
    providerId: 'openai',
    providerModelId: 'gpt-5.3-codex',
    displayName: 'GPT-5.3 Codex',
    family: 'gpt-5.3',
    version: '5.3',
    aliases: ['gpt-5.3-codex', 'best_coding'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-03-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 256_000,
    maxOutputTokens: 64_000,
    latencyProfile: 'balanced',
    capabilities: caps({ reasoning: true, coding: true, agents: true, tools: true, scores: { coding: score(10), agentic: score(8) } }),
    pricing: { inputPerMillionUsd: 2.5, outputPerMillionUsd: 10, currency: 'USD', source: 'inferred' },
  }),
  model({
    id: 'anthropic:claude-fable-5',
    providerId: 'anthropic',
    providerModelId: 'claude-fable-5',
    displayName: 'Claude Fable 5',
    family: 'claude-fable',
    version: '5',
    aliases: ['claude-fable-5'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-06-09',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 1_000_000,
    maxOutputTokens: 128_000,
    latencyProfile: 'slow',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true, vision: true, multimodal: true, structured_output: true,
      scores: { reasoning: score(10, 'provider_declared'), coding: score(10, 'provider_declared'), agentic: score(10, 'provider_declared') },
    }),
    pricing: { inputPerMillionUsd: 10, outputPerMillionUsd: 50, currency: 'USD', source: 'provider_declared' },
    metadata: {
      ...thinkingMeta({
        parameter: 'output_config.effort',
        tiers: ['low', 'medium', 'high', 'extrahigh', 'ultra'],
        defaultTier: 'high',
        notes: 'Mythos-class GA model with safety classifiers; may refuse and offer server-side fallback. Highest Anthropic tier for long-horizon agents.',
      }),
      safetyClassifiers: true,
    },
  }),
  model({
    id: 'anthropic:claude-opus-5',
    providerId: 'anthropic',
    providerModelId: 'claude-opus-5',
    displayName: 'Claude Opus 5',
    family: 'claude-opus',
    version: '5',
    aliases: ['claude-opus-5'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-07-24',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 1_000_000,
    maxOutputTokens: 128_000,
    latencyProfile: 'slow',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true, vision: true, multimodal: true, structured_output: true,
      scores: { reasoning: score(10, 'provider_declared'), coding: score(9, 'provider_declared'), agentic: score(10, 'provider_declared') },
    }),
    pricing: { inputPerMillionUsd: 5, outputPerMillionUsd: 25, currency: 'USD', source: 'provider_declared' },
    metadata: thinkingMeta({
      parameter: 'output_config.effort',
      tiers: ['low', 'medium', 'high', 'extrahigh', 'ultra'],
      defaultTier: 'high',
      notes: 'Adaptive thinking on by default. API `ultra` maps to max effort. Fast mode available on Claude API at 2× list price.',
    }),
  }),
  model({
    id: 'anthropic:claude-sonnet-5',
    providerId: 'anthropic',
    providerModelId: 'claude-sonnet-5',
    displayName: 'Claude Sonnet 5',
    family: 'claude-sonnet',
    version: '5',
    aliases: ['claude-sonnet-5', 'best_coding', 'best_agent'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-06-30',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 1_000_000,
    maxOutputTokens: 128_000,
    latencyProfile: 'balanced',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true, vision: true, multimodal: true,
      scores: { reasoning: score(9, 'provider_declared'), coding: score(10, 'provider_declared'), agentic: score(9, 'provider_declared') },
    }),
    pricing: { inputPerMillionUsd: 3, outputPerMillionUsd: 15, currency: 'USD', source: 'provider_declared' },
    metadata: thinkingMeta({
      parameter: 'output_config.effort',
      tiers: ['low', 'medium', 'high', 'extrahigh'],
      defaultTier: 'high',
      notes: 'Standard Sonnet 5 pricing after introductory period ended 2026-08-31.',
    }),
  }),
  model({
    id: 'anthropic:claude-opus-4-6',
    providerId: 'anthropic',
    providerModelId: 'claude-opus-4-6',
    displayName: 'Claude Opus 4.6',
    family: 'claude-opus',
    version: '4.6',
    aliases: ['claude-opus-4-6'],
    lifecycle: 'DEPRECATED',
    releaseDate: '2026-05-01',
    deprecationDate: '2026-08-01',
    retirementDate: null,
    replacementModelId: 'anthropic:claude-opus-5',
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    latencyProfile: 'slow',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true, vision: true, multimodal: true, structured_output: true,
      scores: { reasoning: score(9), coding: score(8), agentic: score(9) },
    }),
    pricing: { inputPerMillionUsd: 5, outputPerMillionUsd: 25, currency: 'USD', source: 'provider_declared' },
  }),
  model({
    id: 'anthropic:claude-sonnet-4-6',
    providerId: 'anthropic',
    providerModelId: 'claude-sonnet-4-6',
    displayName: 'Claude Sonnet 4.6',
    family: 'claude-sonnet',
    version: '4.6',
    aliases: ['claude-sonnet-4-6'],
    lifecycle: 'DEPRECATED',
    releaseDate: '2026-05-01',
    deprecationDate: '2026-08-01',
    retirementDate: null,
    replacementModelId: 'anthropic:claude-sonnet-5',
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    latencyProfile: 'balanced',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true, vision: true, multimodal: true,
      scores: { reasoning: score(8), coding: score(9), agentic: score(8) },
    }),
    pricing: { inputPerMillionUsd: 3, outputPerMillionUsd: 15, currency: 'USD', source: 'provider_declared' },
  }),
  model({
    id: 'anthropic:claude-haiku-4-5',
    providerId: 'anthropic',
    providerModelId: 'claude-haiku-4-5',
    displayName: 'Claude Haiku 4.5',
    family: 'claude-haiku',
    version: '4.5',
    aliases: ['claude-haiku-4-5', 'best_fast', 'best_cost'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-02-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 200_000,
    maxOutputTokens: 16_000,
    latencyProfile: 'fast',
    capabilities: caps({ reasoning: true, coding: true, tools: true, scores: { reasoning: score(6), coding: score(7) } }),
    pricing: { inputPerMillionUsd: 0.8, outputPerMillionUsd: 4, currency: 'USD', source: 'inferred' },
  }),
  model({
    id: 'gemini:gemini-3.1-pro',
    providerId: 'gemini',
    providerModelId: 'gemini-3.1-pro',
    displayName: 'Gemini 3.1 Pro',
    family: 'gemini-3.1',
    version: '3.1',
    aliases: ['gemini-3.1-pro', 'gemini-3.1-pro-preview', 'best_multimodal', 'best_long_context'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-06-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    latencyProfile: 'balanced',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true, vision: true, audio: true, multimodal: true,
      scores: { reasoning: score(9, 'provider_declared'), coding: score(9), long_context: score(10), agentic: score(8) },
    }),
    pricing: { inputPerMillionUsd: 2, outputPerMillionUsd: 12, currency: 'USD', source: 'provider_declared' },
    metadata: thinkingMeta({
      parameter: 'thinking_level',
      tiers: ['low', 'medium', 'high'],
      defaultTier: 'medium',
      notes: 'Prompts above 200k tokens bill at $4/$18 per million for the entire request. Preview API id gemini-3.1-pro-preview.',
    }),
  }),
  model({
    id: 'gemini:gemini-3.5-flash-lite',
    providerId: 'gemini',
    providerModelId: 'gemini-3.5-flash-lite',
    displayName: 'Gemini 3.5 Flash-Lite',
    family: 'gemini-3.5',
    version: '3.5',
    aliases: ['gemini-3.5-flash-lite', 'best_fast'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-07-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    latencyProfile: 'fast',
    capabilities: caps({ reasoning: true, coding: true, tools: true, vision: true, multimodal: true, scores: { reasoning: score(7), coding: score(7) } }),
    pricing: { inputPerMillionUsd: 0.3, outputPerMillionUsd: 2.5, currency: 'USD', source: 'provider_declared' },
  }),
  model({
    id: 'gemini:gemini-2.5-pro',
    providerId: 'gemini',
    providerModelId: 'gemini-2.5-pro',
    displayName: 'Gemini 2.5 Pro',
    family: 'gemini-2.5',
    version: '2.5',
    aliases: ['gemini-2.5-pro'],
    lifecycle: 'DEPRECATED',
    releaseDate: '2025-06-01',
    deprecationDate: '2026-08-01',
    retirementDate: null,
    replacementModelId: 'gemini:gemini-3.1-pro',
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    latencyProfile: 'balanced',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true, vision: true, audio: true, multimodal: true,
      scores: { reasoning: score(8), coding: score(7), long_context: score(9) },
    }),
    pricing: { inputPerMillionUsd: 1.25, outputPerMillionUsd: 10, currency: 'USD', source: 'inferred' },
  }),
  model({
    id: 'gemini:gemini-2.5-flash',
    providerId: 'gemini',
    providerModelId: 'gemini-2.5-flash',
    displayName: 'Gemini 2.5 Flash',
    family: 'gemini-2.5',
    version: '2.5',
    aliases: ['gemini-2.5-flash'],
    lifecycle: 'DEPRECATED',
    releaseDate: '2025-06-01',
    deprecationDate: '2026-08-01',
    retirementDate: null,
    replacementModelId: 'gemini:gemini-3.5-flash-lite',
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    latencyProfile: 'fast',
    capabilities: caps({ reasoning: true, coding: true, tools: true, vision: true, multimodal: true, scores: { reasoning: score(6) } }),
    pricing: { inputPerMillionUsd: 0.3, outputPerMillionUsd: 2.5, currency: 'USD', source: 'inferred' },
  }),
  model({
    id: 'xai:grok-4.6',
    providerId: 'xai',
    providerModelId: 'grok-4.6',
    displayName: 'Grok 4.6',
    family: 'grok',
    version: '4.6',
    aliases: ['grok-4.6', 'best_reasoning', 'best_coding'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-08-12',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 500_000,
    maxOutputTokens: 32_000,
    latencyProfile: 'balanced',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true, vision: true,
      scores: { reasoning: score(10, 'provider_declared'), coding: score(10, 'provider_declared'), agentic: score(10, 'provider_declared') },
    }),
    pricing: { inputPerMillionUsd: 2, outputPerMillionUsd: 6, currency: 'USD', source: 'provider_declared' },
    metadata: thinkingMeta({
      parameter: 'reasoning_effort',
      tiers: ['low', 'medium', 'high', 'extrahigh'],
      defaultTier: 'high',
      notes: 'DeplAI peak-performance pick at high or extrahigh effort. Reasoning cannot be disabled. Prompts ≥200k tokens use 2× input and output rates.',
    }),
  }),
  model({
    id: 'xai:grok-4.5',
    providerId: 'xai',
    providerModelId: 'grok-4.5',
    displayName: 'Grok 4.5',
    family: 'grok',
    version: '4.5',
    aliases: ['grok-4.5', 'grok-4.5-latest', 'grok-build-latest'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-06-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 500_000,
    maxOutputTokens: 32_000,
    latencyProfile: 'balanced',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true, vision: true,
      scores: { reasoning: score(9, 'provider_declared'), coding: score(9, 'provider_declared'), agentic: score(9, 'provider_declared') },
    }),
    pricing: { inputPerMillionUsd: 2, outputPerMillionUsd: 6, currency: 'USD', source: 'provider_declared' },
    metadata: thinkingMeta({
      parameter: 'reasoning_effort',
      tiers: ['low', 'medium', 'high', 'extrahigh'],
      defaultTier: 'high',
      notes: 'Prior xAI flagship; lower cached-input rate than Grok 4.6. Prompts ≥200k tokens use 2× input and output rates.',
    }),
  }),
  model({
    id: 'xai:grok-4',
    providerId: 'xai',
    providerModelId: 'grok-4',
    displayName: 'Grok 4',
    family: 'grok',
    version: '4',
    aliases: ['grok-4'],
    lifecycle: 'DEPRECATED',
    releaseDate: '2026-01-01',
    deprecationDate: '2026-08-12',
    retirementDate: null,
    replacementModelId: 'xai:grok-4.6',
    contextWindow: 256_000,
    maxOutputTokens: 32_000,
    latencyProfile: 'balanced',
    capabilities: caps({ reasoning: true, coding: true, agents: true, tools: true, vision: true, scores: { reasoning: score(8), coding: score(8) } }),
    pricing: { inputPerMillionUsd: 3, outputPerMillionUsd: 15, currency: 'USD', source: 'provider_declared' },
  }),
  model({
    id: 'minimax:MiniMax-M3-free',
    providerId: 'minimax',
    providerModelId: 'MiniMax-M3-free',
    displayName: 'MiniMax M3 Free',
    family: 'minimax-m',
    version: '3',
    aliases: ['MiniMax-M3-free'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-03-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 1_000_000,
    maxOutputTokens: 131_072,
    latencyProfile: 'balanced',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true, vision: true, multimodal: true,
      scores: { reasoning: score(9), coding: score(9), agentic: score(9), long_context: score(9) },
    }),
    pricing: { inputPerMillionUsd: 0, outputPerMillionUsd: 0, currency: 'USD', source: 'provider_declared' },
    metadata: {
      openrouter_slug: 'minimax/minimax-m3:free',
      notes: 'Free tier on OpenRouter; routed through DeplAI platform key.',
    },
  }),
  model({
    id: 'minimax:MiniMax-M3',
    providerId: 'minimax',
    providerModelId: 'MiniMax-M3',
    displayName: 'MiniMax M3',
    family: 'minimax-m',
    version: '3',
    aliases: ['MiniMax-M3', 'best_reasoning', 'best_agent', 'best_coding'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-06-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 1_000_000,
    maxOutputTokens: 131_072,
    latencyProfile: 'balanced',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true, vision: true, multimodal: true,
      scores: { reasoning: score(10, 'provider_declared'), coding: score(10, 'provider_declared'), agentic: score(10, 'provider_declared'), long_context: score(9) },
    }),
    pricing: { inputPerMillionUsd: 0.6, outputPerMillionUsd: 2.4, currency: 'USD', source: 'provider_declared' },
    metadata: thinkingMeta({
      parameter: 'thinking.type',
      tiers: ['low', 'medium', 'high', 'extrahigh'],
      defaultTier: 'medium',
      notes: 'DeplAI peak-performance pick at high or extrahigh effort. Adaptive thinking default; native multimodal with 1M MSA context.',
    }),
  }),
  model({
    id: 'minimax:MiniMax-M2.7',
    providerId: 'minimax',
    providerModelId: 'MiniMax-M2.7',
    displayName: 'MiniMax M2.7',
    family: 'minimax-m',
    version: '2.7',
    aliases: ['MiniMax-M2.7'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-01-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 204_800,
    maxOutputTokens: 131_072,
    latencyProfile: 'balanced',
    capabilities: caps({
      reasoning: true, coding: true, agents: true, tools: true,
      scores: { reasoning: score(8), coding: score(8), agentic: score(8) },
    }),
    pricing: { inputPerMillionUsd: 0.3, outputPerMillionUsd: 1.2, currency: 'USD', source: 'provider_declared' },
    metadata: thinkingMeta({
      parameter: 'thinking (always on)',
      tiers: ['medium', 'high', 'extrahigh'],
      defaultTier: 'medium',
      notes: 'M2.x models always reason; use MiniMax-M2.7-highspeed when latency matters.',
    }),
  }),
  model({
    id: 'kimi:kimi-k2.5',
    providerId: 'kimi',
    providerModelId: 'kimi-k2.5',
    displayName: 'Kimi K2.5',
    family: 'kimi',
    version: '2.5',
    aliases: ['kimi-k2.5', 'best_long_context'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-01-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 2_000_000,
    maxOutputTokens: 32_000,
    latencyProfile: 'balanced',
    capabilities: caps({ reasoning: true, coding: true, agents: true, tools: true, scores: { long_context: score(10), reasoning: score(8) } }),
    pricing: { inputPerMillionUsd: 0.6, outputPerMillionUsd: 2.5, currency: 'USD', source: 'inferred' },
  }),
  model({
    id: 'openrouter:nemotron-3.5-content-safety-free',
    providerId: 'openrouter',
    providerModelId: 'nemotron-3.5-content-safety-free',
    displayName: 'Nemotron 3.5 Content Safety (Free)',
    family: 'nemotron',
    version: '3.5',
    aliases: ['nemotron-3.5-content-safety-free'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-03-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 128_000,
    maxOutputTokens: 16_000,
    latencyProfile: 'fast',
    capabilities: caps({
      reasoning: true,
      coding: true,
      agents: true,
      scores: { reasoning: score(7), coding: score(6) },
    }),
    pricing: { inputPerMillionUsd: 0, outputPerMillionUsd: 0, currency: 'USD', source: 'provider_declared' },
    metadata: {
      openrouter_slug: 'nvidia/nemotron-3.5-content-safety:free',
      notes: 'Free NVIDIA content-safety model on OpenRouter; useful for triage-oriented remediation passes.',
    },
  }),
  model({
    id: 'glm:glm-5.2-free',
    providerId: 'glm',
    providerModelId: 'glm-5.2-free',
    displayName: 'GLM 5.2 Free',
    family: 'glm',
    version: '5.2',
    aliases: ['glm-5.2-free', 'z-ai/glm-5.2:free'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-03-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    latencyProfile: 'balanced',
    capabilities: caps({
      reasoning: true,
      coding: true,
      agents: true,
      tools: true,
      scores: { coding: score(8), agentic: score(8), reasoning: score(8) },
    }),
    pricing: { inputPerMillionUsd: 0, outputPerMillionUsd: 0, currency: 'USD', source: 'provider_declared' },
    metadata: {
      openrouter_slug: 'z-ai/glm-5.2:free',
      notes: 'Free tier on OpenRouter; routed through DeplAI platform key.',
    },
  }),
  model({
    id: 'glm:glm-5',
    providerId: 'glm',
    providerModelId: 'glm-5',
    displayName: 'GLM-5',
    family: 'glm',
    version: '5',
    aliases: ['glm-5', 'best_coding', 'best_agent'],
    lifecycle: 'ACTIVE',
    releaseDate: '2026-01-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    latencyProfile: 'balanced',
    capabilities: caps({ reasoning: true, coding: true, agents: true, tools: true, vision: true, scores: { coding: score(9), agentic: score(9), reasoning: score(8) } }),
    pricing: { inputPerMillionUsd: 1, outputPerMillionUsd: 4, currency: 'USD', source: 'inferred' },
  }),
  model({
    id: 'groq:llama-3.3-70b-versatile',
    providerId: 'groq',
    providerModelId: 'llama-3.3-70b-versatile',
    displayName: 'Llama 3.3 70B Versatile',
    family: 'llama',
    version: '3.3',
    aliases: ['llama-3.3-70b-versatile', 'best_fast'],
    lifecycle: 'ACTIVE',
    releaseDate: '2024-12-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 128_000,
    maxOutputTokens: 32_768,
    latencyProfile: 'fast',
    modelOwner: 'meta',
    capabilities: caps({ reasoning: true, coding: true, tools: true, scores: { reasoning: score(6), coding: score(7) } }),
    pricing: { inputPerMillionUsd: 0.59, outputPerMillionUsd: 0.79, currency: 'USD', source: 'inferred' },
  }),
  model({
    id: 'groq:llama-3.1-8b-instant',
    providerId: 'groq',
    providerModelId: 'llama-3.1-8b-instant',
    displayName: 'Llama 3.1 8B Instant',
    family: 'llama',
    version: '3.1',
    aliases: ['llama-3.1-8b-instant', 'best_cost'],
    lifecycle: 'ACTIVE',
    releaseDate: '2024-07-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    latencyProfile: 'fast',
    modelOwner: 'meta',
    capabilities: caps({ reasoning: false, coding: true, tools: true, scores: { coding: score(5) } }),
    pricing: { inputPerMillionUsd: 0.05, outputPerMillionUsd: 0.08, currency: 'USD', source: 'inferred' },
  }),
  model({
    id: 'groq:openai/gpt-oss-120b',
    providerId: 'groq',
    providerModelId: 'openai/gpt-oss-120b',
    displayName: 'GPT OSS 120B',
    family: 'gpt-oss',
    version: '120b',
    aliases: ['openai/gpt-oss-120b'],
    lifecycle: 'ACTIVE',
    releaseDate: '2025-08-01',
    deprecationDate: null,
    retirementDate: null,
    replacementModelId: null,
    contextWindow: 131_072,
    maxOutputTokens: 32_768,
    latencyProfile: 'fast',
    modelOwner: 'openai',
    capabilities: caps({ reasoning: true, coding: true, tools: true, scores: { reasoning: score(8), coding: score(8) } }),
    pricing: { inputPerMillionUsd: 0.15, outputPerMillionUsd: 0.6, currency: 'USD', source: 'inferred' },
  }),
];

export const SEED_MODELS: CanonicalModel[] = seed;

export const ALIAS_CAPABILITY: Record<string, CapabilityKey | 'any'> = {
  best: 'any',
  best_reasoning: 'reasoning',
  best_coding: 'coding',
  best_agent: 'agentic',
  best_fast: 'any',
  best_cost: 'any',
  best_long_context: 'long_context',
  best_multimodal: 'any',
  best_vision: 'vision',
  best_structured_output: 'structured_output',
};

export function modelIdFor(providerId: ProviderId | string, providerModelId: string): string {
  return `${providerId}:${providerModelId}`;
}

export function isSelectableLifecycle(lifecycle: ModelLifecycle): boolean {
  return lifecycle === 'ACTIVE' || lifecycle === 'PREVIEW' || lifecycle === 'DISCOVERED';
}
