# Azure Service Categories Mapper
# Maps service identifiers to their display names

mapper = {
    # Analytics
    'analysis services': 'AnalysisServices',
    'data explorer': 'DataExplorerClusters',
    'data explorer cluster': 'DataExplorerClusters',
    'kusto': 'DataExplorerClusters',
    'data factory': 'DataFactories',
    'data factories': 'DataFactories',
    'data lake analytics': 'DataLakeAnalytics',
    'event hub': 'EventHubs',
    'event hubs': 'EventHubs',
    'log analytics': 'LogAnalyticsWorkspaces',
    'log analytics workspace': 'LogAnalyticsWorkspaces',
    'stream analytics': 'StreamAnalyticsJobs',
    'stream analytics job': 'StreamAnalyticsJobs',
    'synapse': 'SynapseAnalytics',
    'synapse analytics': 'SynapseAnalytics',
    'databricks': 'Databricks',
    'azure databricks': 'Databricks',

    # Application / Web
    'api management': 'APIManagement',
    'apim': 'APIManagement',
    'app service': 'AppServices',
    'app services': 'AppServices',
    'web app': 'AppServices',
    'web apps': 'AppServices',
    'container app': 'ContainerApps',
    'container apps': 'ContainerApps',
    'event grid domain': 'EventGridDomains',
    'event grid subscription': 'EventGridSubscriptions',
    'event grid topic': 'EventGridTopics',
    'event grid': 'EventGridTopics',
    'logic app': 'LogicApps',
    'logic apps': 'LogicApps',
    'service bus': 'ServiceBus',
    'web application firewall': 'WebApplicationFirewallWAF',
    'waf': 'WebApplicationFirewallWAF',
    'static web app': 'StaticWebApps',
    'static web apps': 'StaticWebApps',

    # Compute
    'availability set': 'AvailabilitySets',
    'availability sets': 'AvailabilitySets',
    'batch account': 'BatchAccounts',
    'batch accounts': 'BatchAccounts',
    'cloud service': 'CloudServices',
    'cloud services': 'CloudServices',
    'container instance': 'ContainerInstances',
    'container instances': 'ContainerInstances',
    'aci': 'ContainerInstances',
    'container registry': 'ContainerRegistries',
    'container registries': 'ContainerRegistries',
    'acr': 'ContainerRegistries',
    'disk': 'Disks',
    'managed disk': 'Disks',
    'managed disks': 'Disks',
    'function app': 'FunctionApps',
    'function apps': 'FunctionApps',
    'azure function': 'FunctionApps',
    'azure functions': 'FunctionApps',
    'host': 'Host',
    'dedicated host': 'Host',
    'image definition': 'ImageDefinitions',
    'image version': 'ImageVersions',
    'kubernetes service': 'KubernetesServices',
    'kubernetes services': 'KubernetesServices',
    'aks': 'KubernetesServices',
    'scale set': 'ScaleSets',
    'scale sets': 'ScaleSets',
    'virtual machine scale set': 'ScaleSets',
    'vmss': 'ScaleSets',
    'virtual machine': 'VirtualMachines',
    'vm': 'VirtualMachines',
    'virtual machines': 'VirtualMachines',
    'vms': 'VirtualMachines',

    # Database
    'cache for redis': 'CacheForRedis',
    'redis': 'CacheForRedis',
    'azure cache for redis': 'CacheForRedis',
    'cosmos db': 'Cosmosdb',
    'database for mariadb': 'DatabaseForMariadbServers',
    'mariadb': 'DatabaseForMariadbServers',
    'database for mysql': 'DatabaseForMysqlServers',
    'mysql': 'DatabaseForMysqlServers',
    'database for postgresql': 'DatabaseForPostgresqlServers',
    'postgresql': 'DatabaseForPostgresqlServers',
    'postgres': 'DatabaseForPostgresqlServers',
    'sql database': 'SQLDatabases',
    'sql databases': 'SQLDatabases',
    'azure sql': 'SQLDatabases',
    'sql managed instance': 'SQLManagedInstances',
    'sql managed instances': 'SQLManagedInstances',

    # DevOps
    'artifacts': 'Artifacts',
    'azure artifacts': 'Artifacts',
    'devops': 'Devops',
    'azure devops': 'Devops',
    'pipelines': 'Pipelines',
    'azure pipelines': 'Pipelines',
    'repos': 'Repos',
    'azure repos': 'Repos',
    'test plans': 'TestPlans',
    'azure test plans': 'TestPlans',

    # General / Management
    'advisor': 'Advisor',
    'azure advisor': 'Advisor',
    'cost management': 'Billing',
    'billing': 'Billing',
    'azure portal': 'Azureportal',
    'policy': 'Policy',
    'azure policy': 'Policy',
    'resource': 'Resource',
    'azure resource': 'Resource',
    'resource group': 'Resourcegroup',
    'resource groups': 'Resourcegroup',
    'service health': 'Servicehealth',
    'subscription': 'Subscription',
    'subscriptions': 'Subscription',
    'azure subscription': 'Subscription',
    'tag': 'Tags',
    'tags': 'Tags',

    # Identity
    'azure ad': 'Azuread',
    'azure active directory': 'Azuread',
    'active directory': 'Azuread',
    'aad': 'Azuread',
    'azure ad b2c': 'AzureADB2C',
    'azure ad domain services': 'AzureADDomainServices',
    'azure ad identity protection': 'AzureADIdentityProtection',

    # Integration
    # Most are covered under Application / Web

    # IoT
    'iot hub': 'IotHub',
    'iot central': 'IoTCentral',
    'iot edge': 'IotEdge',

    # Migration
    'azure migrate': 'AzureMigrate',
    'database migration service': 'DatabaseMigrationService',

    # Recovery
    'backup vault': 'RecoveryServicesVaults',

    # ML & AI
    'bot service': 'BotServices',
    'bot services': 'BotServices',
    'cognitive services': 'CognitiveServices',
    'machine learning': 'MachineLearningServiceWorkspaces',
    'azure machine learning': 'MachineLearningServiceWorkspaces',
    'ml workspace': 'MachineLearningServiceWorkspaces',

    # Monitor
    'monitor': 'Monitor',
    'azure monitor': 'Monitor',

    # Network
    'application gateway': 'ApplicationGateway',
    'app gateway': 'ApplicationGateway',
    'ddos protection plan': 'DdosProtectionPlans',
    'ddos protection': 'DdosProtectionPlans',
    'dns zone': 'DNSZones',
    'dns': 'DNSZones',
    'expressroute circuit': 'ExpressRouteCircuits',
    'expressroute': 'ExpressRouteCircuits',
    'firewall': 'Firewalls',
    'azure firewall': 'Firewalls',
    'load balancer': 'LoadBalancers',
    'load balancers': 'LoadBalancers',
    'network interface': 'NetworkInterfaces',
    'nic': 'NetworkInterfaces',
    'network watcher': 'NetworkWatcher',
    'private link': 'PrivateLink',
    'public ip address': 'PublicIpAddresses',
    'public ip': 'PublicIpAddresses',
    'route table': 'RouteTables',
    'route tables': 'RouteTables',
    'traffic manager profile': 'TrafficManagerProfiles',
    'traffic manager': 'TrafficManagerProfiles',
    'virtual network': 'VirtualNetworks',
    'vnet': 'VirtualNetworks',
    'virtual networks': 'VirtualNetworks',
    'vpn gateway': 'VpnGateways',

    # Security
    'application security group': 'ApplicationSecurityGroups',
    'asg': 'ApplicationSecurityGroups',
    'key vault': 'KeyVaults',
    'key vaults': 'KeyVaults',
    'security center': 'SecurityCenter',
    'azure security center': 'SecurityCenter',
    'sentinel': 'Sentinel',
    'azure sentinel': 'Sentinel',

    # Storage
    'storage account': 'StorageAccounts',
    'storage accounts': 'StorageAccounts',
    'blob storage': 'BlobStorage',
    'data lake storage': 'DataLakeStorage',
    'adls': 'DataLakeStorage',
    'azure files': 'Files',
    'file share': 'Files',
    'azure netapp files': 'Netapp',
    'netapp': 'Netapp',
    'queue storage': 'Queues',
    'azure queues': 'Queues',
    'table storage': 'Tables',
    'azure tables': 'Tables'
} 