import os
from github import Github, GithubException
from langchain_core.tools import BaseTool
from pydantic import BaseModel, Field
import logging

logger = logging.getLogger(__name__)

class GithubDeployerInput(BaseModel):
    """Input schema for the GithubDeployerTool."""
    project_name: str = Field(description="The name of the project to be deployed.")
    output_directory: str = Field(description="The local directory containing the Terraform code and artifacts.")
    cloud_provider: str = Field(description="The cloud provider (e.g., 'aws', 'gcp', 'azure').")
    github_token: str = Field(description="The GitHub Personal Access Token.")
    # AWS Credentials
    aws_access_key_id: str | None = Field(default=None, description="The AWS Access Key ID for repository secrets.")
    aws_secret_access_key: str | None = Field(default=None, description="The AWS Secret Access Key for repository secrets.")
    # Azure Credentials
    azure_client_id: str | None = Field(default=None, description="The Azure Client ID for repository secrets.")
    azure_tenant_id: str | None = Field(default=None, description="The Azure Tenant ID for repository secrets.")
    azure_subscription_id: str | None = Field(default=None, description="The Azure Subscription ID for repository secrets.")
    # GCP Credentials
    gcp_credentials_json: str | None = Field(default=None, description="The GCP Service Account JSON for repository secrets.")


class GithubDeployerTool(BaseTool):
    """
    A tool to manage the GitOps deployment of a Terraform project to GitHub.
    """
    name: str = "github_deployer"
    description: str = (
        "Handles the entire GitOps deployment process: creates a private GitHub repository, "
        "populates it with the Terraform project files, configures a CI/CD workflow, "
        "and sets up necessary secrets."
    )
    args_schema: type[BaseModel] = GithubDeployerInput

    def _run(
        self, 
        project_name: str, 
        output_directory: str, 
        cloud_provider: str, 
        github_token: str,
        aws_access_key_id: str = None,
        aws_secret_access_key: str = None,
        azure_client_id: str = None,
        azure_tenant_id: str = None,
        azure_subscription_id: str = None,
        gcp_credentials_json: str = None
    ) -> str:
        """
        Executes the full GitOps deployment workflow.
        """
        logger.info(f"🚀 Initializing GitOps deployment for project '{project_name}'...")

        # --- 1. Authenticate with GitHub ---
        if not github_token:
            logger.error("❌ GitHub token was not provided.")
            return "Error: GitHub Token is required to proceed with deployment."

        try:
            g = Github(github_token)
            user = g.get_user()
            logger.info(f"✅ Successfully authenticated with GitHub as '{user.login}'.")
        except GithubException as e:
            logger.error(f"❌ GitHub authentication failed: {e.status} {e.data}")
            return f"Error: GitHub authentication failed. Please check your token. Status: {e.status}"
        except Exception as e:
            logger.error(f"❌ An unexpected error occurred during GitHub authentication: {e}")
            return f"Error: An unexpected error occurred during GitHub authentication. Details: {e}"

        # --- 2. Create GitHub Repository ---
        try:
            repo_name = project_name.replace(" ", "_").lower()
            logger.info(f"Checking if repository '{repo_name}' already exists...")
            
            try:
                repo = g.get_repo(f"{user.login}/{repo_name}")
                logger.info(f"✅ Repository '{repo.full_name}' already exists. Proceeding.")
            except GithubException as e:
                if e.status == 404:
                    logger.info(f"Repository '{repo_name}' does not exist. Creating it...")
                    repo = user.create_repo(
                        name=repo_name,
                        description=f"Terraform project '{project_name}' generated by DeplAI.",
                        private=True,
                        auto_init=True 
                    )
                    logger.info(f"✅ Successfully created private repository: {repo.full_name}")
                else:
                    raise e

        except Exception as e:
            logger.error(f"❌ Failed to create or access GitHub repository: {e}")
            return f"Error: Failed to create or access the repository. Details: {e}"

        # --- 3. Set Repository Secrets (if provided) ---
        try:
            if cloud_provider == 'aws' and aws_access_key_id and aws_secret_access_key:
                logger.info(f"Setting AWS secrets in '{repo.full_name}' repository...")
                repo.create_secret("AWS_ACCESS_KEY_ID", aws_access_key_id)
                repo.create_secret("AWS_SECRET_ACCESS_KEY", aws_secret_access_key)
                logger.info("✅ Successfully set AWS secrets.")
            
            elif cloud_provider == 'azure' and all([azure_client_id, azure_tenant_id, azure_subscription_id]):
                logger.info(f"Setting Azure secrets in '{repo.full_name}' repository...")
                repo.create_secret("AZURE_CLIENT_ID", azure_client_id)
                repo.create_secret("AZURE_TENANT_ID", azure_tenant_id)
                repo.create_secret("AZURE_SUBSCRIPTION_ID", azure_subscription_id)
                logger.info("✅ Successfully set Azure secrets.")

            elif cloud_provider == 'gcp' and gcp_credentials_json:
                logger.info(f"Setting GCP secrets in '{repo.full_name}' repository...")
                repo.create_secret("GCP_CREDENTIALS", gcp_credentials_json)
                logger.info("✅ Successfully set GCP secrets.")

        except GithubException as e:
            # A 422 status code often means the secret already exists.
            if e.status == 422:
                logger.warning(f"Could not create secrets in '{repo.full_name}'. They may already exist. Attempting to continue.")
            else:
                logger.error(f"❌ Failed to set repository secrets due to a GitHub API error: {e}")
        except Exception as e:
            logger.error(f"❌ An unexpected error occurred while setting repository secrets: {e}")
            # We will continue, but the pipeline will likely fail.
        
        # --- 4. Upload Project Files ---
        try:
            logger.info(f"Uploading files from '{output_directory}' to repository '{repo.full_name}'...")
            
            # --- CRITICAL DIAGNOSTIC LOG ---
            logger.info(f"GITHUB_DEPLOYER_TOOL: Walking directory path: '{output_directory}'")
            if not output_directory or not os.path.exists(output_directory):
                logger.error("GITHUB_DEPLOYER_TOOL: The provided output directory does not exist or is empty!")
                return "Error: The project output directory could not be found on the server."
            # --- END DIAGNOSTIC LOG ---

            commit_files = []
            for root, _, files in os.walk(output_directory):
                # --- CRITICAL DIAGNOSTIC LOG ---
                logger.info(f"GITHUB_DEPLOYER_TOOL: Inside '{root}', found files: {files}")
                # --- END DIAGNOSTIC LOG ---
                for filename in files:
                    local_path = os.path.join(root, filename)
                    # Calculate the path relative to the output_directory for the repo
                    repo_path = os.path.relpath(local_path, output_directory)
                    
                    # Read file content as binary
                    with open(local_path, 'rb') as f:
                        content = f.read()
                    
                    commit_files.append((repo_path, content))

            if not commit_files:
                logger.warning(f"No files found to upload in '{output_directory}'.")
            else:
                for repo_path, content in commit_files:
                    # Determine commit message
                    if repo_path.endswith(".zip"):
                        commit_message = f"feat: Add deployment package {os.path.basename(repo_path)}"
                    else:
                        commit_message = f"feat: Add {os.path.basename(repo_path)}"

                    # Upload the file
                    self._upload_file_to_repo(
                        repo=repo,
                        file_path=repo_path.replace(os.sep, '/'), # Ensure forward slashes for repo path
                        file_content=content,
                        commit_message=commit_message
                    )
            
            logger.info("✅ Successfully uploaded all project files.")

        except Exception as e:
            logger.error(f"❌ Failed to upload project files: {e}", exc_info=True)
            return f"Error: Failed to upload files. Details: {e}"

        # --- 5. Configure CI/CD Workflow ---
        try:
            logger.info("Configuring CI/CD workflow...")
            template_path = f"cicd_templates/{cloud_provider}_deploy_template.yml"
            
            if not os.path.exists(template_path):
                logger.error(f"❌ CI/CD template not found at '{template_path}'")
                return f"Error: No deployment template available for '{cloud_provider}'."

            with open(template_path, 'r', encoding='utf-8') as f:
                workflow_content = f.read()

            # TODO: Dynamically get these values from the plan/code
            aws_region = "us-east-1"
            tf_version = "1.5.0"

            # Replace placeholders
            workflow_content = workflow_content.replace("##AWS_REGION##", aws_region)
            workflow_content = workflow_content.replace("##TF_VERSION##", tf_version)

            workflow_path = ".github/workflows/deploy.yml"
            self._upload_file_to_repo(
                repo=repo,
                file_path=workflow_path,
                file_content=workflow_content.encode('utf-8'), # Encode to bytes
                commit_message="feat: Add CI/CD deployment workflow"
            )
            logger.info(f"✅ Successfully configured and uploaded CI/CD workflow to '{workflow_path}'.")

        except Exception as e:
            logger.error(f"❌ Failed to configure CI/CD workflow: {e}")
            return f"Error: Failed to set up the deployment workflow. Details: {e}"

        # --- Final Confirmation ---
        confirmation_message = (
            f"✅ Deployment pipeline for '{repo.full_name}' is fully configured. "
            f"Pushing to the 'main' branch will now trigger a Terraform deployment."
        )
        
        logger.info(confirmation_message)
        return confirmation_message

    def _upload_file_to_repo(self, repo, file_path: str, file_content: bytes, commit_message: str):
        """Helper method to upload or update a file in a GitHub repository."""
        try:
            # Check if the file already exists to update it
            contents = repo.get_contents(file_path, ref="main")
            repo.update_file(
                path=contents.path,
                message=commit_message,
                content=file_content,
                sha=contents.sha,
                branch="main"
            )
            logger.info(f"  - Updated file: {file_path}")
        except GithubException as e:
            if e.status == 404:
                # If the file does not exist, create it
                repo.create_file(
                    path=file_path,
                    message=commit_message,
                    content=file_content,
                    branch="main"
                )
                logger.info(f"  - Created file: {file_path}")
            else:
                raise

    async def _arun(self, *args, **kwargs) -> str:
        """Asynchronous version of the _run method."""
        # This should be properly implemented if async is needed.
        # For now, we raise an error to avoid unexpected behavior.
        raise NotImplementedError("Asynchronous execution is not implemented for GithubDeployerTool.") 