import type { ProviderDefinition, ProviderId } from '../types';

export const PROVIDER_DEFINITIONS: ProviderDefinition[] = [
  {
    id: 'openai',
    name: 'openai',
    displayName: 'OpenAI',
    status: 'active',
    documentationUrl: 'https://platform.openai.com/docs/models',
    apiBaseUrl: 'https://api.openai.com/v1',
    supportsPlatformCredentials: true,
    supportsByok: true,
    supportsModelDiscovery: true,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsAudio: true,
    supportsEmbeddings: true,
    supportsBatch: true,
    supportsReasoning: true,
    supportsStructuredOutput: true,
    supportsOpenaiCompatibility: true,
    authenticationType: 'bearer',
    credentialSchema: {
      secretLabel: 'API key',
      placeholder: 'sk-...',
      helpUrl: 'https://platform.openai.com/api-keys',
    },
    envKeyNames: ['OPENAI_API_KEY'],
    brandColor: '#10a37f',
  },
  {
    id: 'anthropic',
    name: 'anthropic',
    displayName: 'Anthropic',
    status: 'active',
    documentationUrl: 'https://docs.anthropic.com/en/docs/about-claude/models',
    apiBaseUrl: 'https://api.anthropic.com',
    supportsPlatformCredentials: true,
    supportsByok: true,
    supportsModelDiscovery: true,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsAudio: false,
    supportsEmbeddings: false,
    supportsBatch: true,
    supportsReasoning: true,
    supportsStructuredOutput: true,
    supportsOpenaiCompatibility: false,
    authenticationType: 'api_key',
    credentialSchema: {
      secretLabel: 'API key',
      placeholder: 'sk-ant-...',
      helpUrl: 'https://console.anthropic.com/settings/keys',
    },
    envKeyNames: ['ANTHROPIC_API_KEY', 'CLAUDE_API_KEY'],
    brandColor: '#d97757',
  },
  {
    id: 'minimax',
    name: 'minimax',
    displayName: 'MiniMax',
    status: 'active',
    documentationUrl: 'https://platform.minimax.io/docs',
    apiBaseUrl: 'https://api.minimax.io/v1',
    supportsPlatformCredentials: true,
    supportsByok: true,
    supportsModelDiscovery: true,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsAudio: true,
    supportsEmbeddings: false,
    supportsBatch: false,
    supportsReasoning: true,
    supportsStructuredOutput: true,
    supportsOpenaiCompatibility: true,
    authenticationType: 'bearer',
    credentialSchema: {
      secretLabel: 'API key',
      placeholder: 'eyJ...',
      helpUrl: 'https://platform.minimax.io',
    },
    envKeyNames: ['MINIMAX_API_KEY'],
    brandColor: '#ef4444',
  },
  {
    id: 'xai',
    name: 'xai',
    displayName: 'xAI / Grok',
    status: 'active',
    documentationUrl: 'https://docs.x.ai/docs/models',
    apiBaseUrl: 'https://api.x.ai/v1',
    supportsPlatformCredentials: true,
    supportsByok: true,
    supportsModelDiscovery: true,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsAudio: false,
    supportsEmbeddings: false,
    supportsBatch: false,
    supportsReasoning: true,
    supportsStructuredOutput: true,
    supportsOpenaiCompatibility: true,
    authenticationType: 'bearer',
    credentialSchema: {
      secretLabel: 'API key',
      placeholder: 'xai-...',
      helpUrl: 'https://console.x.ai',
    },
    envKeyNames: ['XAI_API_KEY'],
    brandColor: '#e5e5e5',
  },
  {
    id: 'gemini',
    name: 'gemini',
    displayName: 'Google Gemini',
    status: 'active',
    documentationUrl: 'https://ai.google.dev/gemini-api/docs/models',
    apiBaseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    supportsPlatformCredentials: true,
    supportsByok: true,
    supportsModelDiscovery: true,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsAudio: true,
    supportsEmbeddings: true,
    supportsBatch: true,
    supportsReasoning: true,
    supportsStructuredOutput: true,
    supportsOpenaiCompatibility: true,
    authenticationType: 'bearer',
    credentialSchema: {
      secretLabel: 'API key',
      placeholder: 'AIza...',
      helpUrl: 'https://aistudio.google.com/apikey',
    },
    envKeyNames: ['GEMINI_API_KEY', 'GOOGLE_API_KEY', 'GOOGLE_GENERATIVE_AI_API_KEY'],
    brandColor: '#4285f4',
  },
  {
    id: 'kimi',
    name: 'kimi',
    displayName: 'Kimi / Moonshot',
    status: 'active',
    documentationUrl: 'https://platform.moonshot.ai/docs',
    apiBaseUrl: 'https://api.moonshot.ai/v1',
    supportsPlatformCredentials: true,
    supportsByok: true,
    supportsModelDiscovery: true,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsAudio: false,
    supportsEmbeddings: false,
    supportsBatch: false,
    supportsReasoning: true,
    supportsStructuredOutput: true,
    supportsOpenaiCompatibility: true,
    authenticationType: 'bearer',
    credentialSchema: {
      secretLabel: 'API key',
      placeholder: 'sk-...',
      helpUrl: 'https://platform.moonshot.ai',
    },
    envKeyNames: ['KIMI_API_KEY', 'MOONSHOT_API_KEY'],
    brandColor: '#3b82f6',
  },
  {
    id: 'glm',
    name: 'glm',
    displayName: 'GLM / Z.AI',
    status: 'active',
    documentationUrl: 'https://docs.z.ai',
    apiBaseUrl: 'https://api.z.ai/api/paas/v4',
    supportsPlatformCredentials: true,
    supportsByok: true,
    supportsModelDiscovery: true,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsAudio: false,
    supportsEmbeddings: true,
    supportsBatch: false,
    supportsReasoning: true,
    supportsStructuredOutput: true,
    supportsOpenaiCompatibility: true,
    authenticationType: 'bearer',
    credentialSchema: {
      secretLabel: 'API key',
      placeholder: '....',
      helpUrl: 'https://z.ai',
    },
    envKeyNames: ['GLM_API_KEY', 'ZAI_API_KEY', 'Z_AI_API_KEY'],
    brandColor: '#6366f1',
  },
  {
    id: 'groq',
    name: 'groq',
    displayName: 'Groq',
    status: 'active',
    documentationUrl: 'https://console.groq.com/docs/models',
    apiBaseUrl: 'https://api.groq.com/openai/v1',
    supportsPlatformCredentials: true,
    supportsByok: true,
    supportsModelDiscovery: true,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsAudio: true,
    supportsEmbeddings: false,
    supportsBatch: false,
    supportsReasoning: true,
    supportsStructuredOutput: true,
    supportsOpenaiCompatibility: true,
    authenticationType: 'bearer',
    credentialSchema: {
      secretLabel: 'API key',
      placeholder: 'gsk_...',
      helpUrl: 'https://console.groq.com/keys',
    },
    envKeyNames: ['GROQ_API_KEY'],
    brandColor: '#f97316',
  },
  {
    id: 'openrouter',
    name: 'openrouter',
    displayName: 'OpenRouter',
    status: 'active',
    documentationUrl: 'https://openrouter.ai/docs',
    apiBaseUrl: 'https://openrouter.ai/api/v1',
    supportsPlatformCredentials: true,
    supportsByok: true,
    supportsModelDiscovery: true,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    supportsAudio: false,
    supportsEmbeddings: false,
    supportsBatch: false,
    supportsReasoning: true,
    supportsStructuredOutput: true,
    supportsOpenaiCompatibility: true,
    authenticationType: 'bearer',
    credentialSchema: {
      secretLabel: 'API key',
      placeholder: 'sk-or-v1-...',
      helpUrl: 'https://openrouter.ai/keys',
    },
    envKeyNames: ['OPENROUTER_API_KEY'],
    brandColor: '#38bdf8',
  },
];

export function getProviderDefinition(id: string): ProviderDefinition | undefined {
  return PROVIDER_DEFINITIONS.find((provider) => provider.id === id);
}

export const LEGACY_PROVIDER_MAP: Record<string, ProviderId> = {
  claude: 'anthropic',
  anthropic: 'anthropic',
  openai: 'openai',
  google: 'gemini',
  gemini: 'gemini',
  groq: 'groq',
  openrouter: 'openrouter',
  minimax: 'minimax',
  xai: 'xai',
  grok: 'xai',
  kimi: 'kimi',
  moonshot: 'kimi',
  glm: 'glm',
  zai: 'glm',
  'z.ai': 'glm',
  ollama: 'ollama',
};

export function canonicalizeProviderId(input: string | null | undefined): ProviderId | null {
  if (!input) return null;
  const key = input.trim().toLowerCase();
  return LEGACY_PROVIDER_MAP[key] ?? (PROVIDER_DEFINITIONS.some((p) => p.id === key) ? (key as ProviderId) : null);
}
