"""DAST policy constants and error codes.

Authorization decisions are deterministic application code. The LangGraph agent
must never invent or override these values.
"""

from __future__ import annotations

POLICY_VERSION = "2026.08.1"

AUTHZ_PENDING = "PENDING"
AUTHZ_VERIFIED = "VERIFIED"
AUTHZ_REJECTED = "REJECTED"
AUTHZ_EXPIRED = "EXPIRED"
AUTHZ_REVOKED = "REVOKED"

SCOPE_HOST = "VERIFIED_HOST"
SCOPE_DOMAIN = "VERIFIED_DOMAIN"
SCOPE_PROJECT_ASSET = "PROJECT_ASSET"

METHOD_DNS = "DNS_TXT"
METHOD_HTTP = "HTTP"
METHOD_PROJECT = "PROJECT_DEPLOYMENT"

PROFILE_BASELINE = "BASELINE"
PROFILE_FULL = "FULL"
PROFILE_API = "API"

INTENT_PASSIVE = "PASSIVE"
INTENT_ACTIVE = "ACTIVE"
INTENT_API_ACTIVE = "API_ACTIVE"

COMPLIANT = "COMPLIANT"
NON_COMPLIANT = "NON_COMPLIANT"
BLOCKED_UNAUTHORIZED = "BLOCKED_UNAUTHORIZED"
BLOCKED_UNSAFE_TARGET = "BLOCKED_UNSAFE_TARGET"
PENDING_VERIFICATION = "PENDING_VERIFICATION"
SCAN_FAILED = "SCAN_FAILED"
SCAN_INCOMPLETE = "SCAN_INCOMPLETE"

DAST_TARGET_NOT_AUTHORIZED = "DAST_TARGET_NOT_AUTHORIZED"
DAST_DOMAIN_NOT_VERIFIED = "DAST_DOMAIN_NOT_VERIFIED"
DAST_VERIFICATION_EXPIRED = "DAST_VERIFICATION_EXPIRED"
DAST_VERIFICATION_REVOKED = "DAST_VERIFICATION_REVOKED"
DAST_TARGET_OUTSIDE_SCOPE = "DAST_TARGET_OUTSIDE_SCOPE"
DAST_PRIVATE_IP_BLOCKED = "DAST_PRIVATE_IP_BLOCKED"
DAST_UNSAFE_TARGET = "DAST_UNSAFE_TARGET"
DAST_INVALID_TARGET = "DAST_INVALID_TARGET"
DAST_REDIRECT_OUT_OF_SCOPE = "DAST_REDIRECT_OUT_OF_SCOPE"
DAST_DNS_REBINDING_BLOCKED = "DAST_DNS_REBINDING_BLOCKED"
DAST_GRANT_INVALID = "DAST_GRANT_INVALID"

REASON_PROJECT_ASSET = "PROJECT_ASSET"
REASON_VERIFIED_DOMAIN = "VERIFIED_DOMAIN"
REASON_VERIFIED_HOST = "VERIFIED_HOST"
REASON_NOT_ASSOCIATED = "NOT_ASSOCIATED_WITH_PROJECT"
REASON_DOMAIN_NOT_VERIFIED = "DOMAIN_NOT_VERIFIED"
REASON_EXPIRED = "VERIFICATION_EXPIRED"
REASON_REVOKED = "VERIFICATION_REVOKED"
REASON_OUTSIDE_SCOPE = "TARGET_OUTSIDE_SCOPE"
REASON_UNSAFE = "UNSAFE_NETWORK_TARGET"
REASON_INVALID = "INVALID_TARGET"

AUDIT_ASSET_CREATED = "DAST_ASSET_CREATED"
AUDIT_DOMAIN_VERIFICATION_STARTED = "DAST_DOMAIN_VERIFICATION_STARTED"
AUDIT_DOMAIN_VERIFIED = "DAST_DOMAIN_VERIFIED"
AUDIT_DOMAIN_REVOKED = "DAST_DOMAIN_REVOKED"
AUDIT_SCAN_AUTHORIZED = "DAST_SCAN_AUTHORIZED"
AUDIT_SCAN_REJECTED = "DAST_SCAN_REJECTED"
AUDIT_SCAN_STARTED = "DAST_SCAN_STARTED"
AUDIT_ZAP_STARTED = "DAST_ZAP_STARTED"
AUDIT_ZAP_FAILED = "DAST_ZAP_FAILED"
AUDIT_SCAN_COMPLETED = "DAST_SCAN_COMPLETED"
AUDIT_SCAN_CANCELLED = "DAST_SCAN_CANCELLED"
AUDIT_SCAN_TIMED_OUT = "DAST_SCAN_TIMED_OUT"
AUDIT_SCAN_RESULTS_PERSISTED = "DAST_SCAN_RESULTS_PERSISTED"

USER_NOT_AUTHORIZED = (
    "This target is not associated with the selected project "
    "and ownership has not been verified."
)
USER_DOMAIN_NOT_VERIFIED = (
    "Ownership of this domain has not been verified for the selected project."
)
