"""
This module defines the Planner agent, which is responsible for taking a high-level user query
and breaking it down into a structured plan of cloud resources.
"""
import os
import json
import base64
import hashlib
from typing import List, Dict, Optional, Any

from openai import OpenAI
from pydantic.v1 import BaseModel, Field, ValidationError
from langchain_openai import ChatOpenAI

from utils.rag_logger import get_rag_logger
from agent.prompts import get_planner_system_prompt, get_fix_planning_system_prompt

logger = get_rag_logger(__name__)

class Resource(BaseModel):
    """
    Represents a single cloud resource in the plan.
    """
    name: str = Field(description="A unique, descriptive name for the resource (e.g., 'main_vpc', 'public_web_server_sg').")
    resource_type: str = Field(description="The Terraform resource type (e.g., 'aws_vpc', 'aws_instance', 'aws_security_group').")
    description: str = Field(description="A detailed description of the resource's purpose and configuration, including its relationships to other resources.")
    dependencies: Optional[List[str]] = Field(None, description="A list of resource names that this resource depends on.")

class Variable(BaseModel):
    """
    Represents a single input variable in the plan.
    """
    name: str = Field(description="The name of the input variable.")
    description: str = Field(description="A brief description of the variable.")
    type: str = Field(description="The Terraform variable type, e.g., 'string', 'number'.")
    default: Optional[Any] = Field(None, description="A default value for the variable.")

class Output(BaseModel):
    """
    Represents a single output value in the plan.
    """
    name: str = Field(description="The name of the output value.")
    description: str = Field(description="A brief description of the output.")
    value: str = Field(description="The Terraform expression for the value, e.g., 'aws_instance.web_server.public_ip'.")

class Plan(BaseModel):
    """
    Represents the structured infrastructure plan generated by the Planner agent.
    """
    summary: str = Field(description="A brief summary of the infrastructure plan.")
    resources: List[Resource] = Field(description="A list of the cloud resources required to fulfill the user's request.")
    variables: Optional[List[Variable]] = Field([], description="A list of input variables for the Terraform configuration.")
    outputs: Optional[List[Output]] = Field([], description="A list of output values from the Terraform configuration.")

class Planner:
    """
    The Planner agent uses an LLM to decompose a high-level request into a structured plan.
    """
    def __init__(self, llm_model_name: str = "gpt-4.1"):
        try:
            self.client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
            self.model = llm_model_name
            self.system_prompt = get_planner_system_prompt()

        except ImportError:
            raise ImportError("openai is not installed. Please install it with `pip install openai`")

    def generate_plan(self, query: str, user_code_path: Optional[str] = None, s3_file_list: Optional[List[str]] = None) -> Plan:
        """
        Calls the LLM to generate a plan from the user's query.
        """
        logger.info(f"🧠 Generating plan for query: '{query}'")
        
        system_prompt = self.system_prompt
        user_prompt = f"Here is the user request:\n\n{query}"

        # Logic for Lambda function code
        if user_code_path and os.path.basename(user_code_path).endswith('.zip') and not s3_file_list:
            logger.info(f"Planner is aware of user LAMBDA code file: {user_code_path}")
            file_name = os.path.basename(user_code_path)
            
            file_context_prompt = (
                "**CRITICAL INSTRUCTIONS for AWS Lambda Function Deployment:**\n"
                "The user has provided an application code bundle for a Lambda function. "
                f"Its filename is '{file_name}'. Your plan MUST include the following resources:\n"
                "1.  **An `aws_iam_role` for the Lambda function's execution.**\n"
                "    - The `assume_role_policy` MUST allow the 'lambda.amazonaws.com' service to assume the role.\n"
                "2.  **An `aws_iam_role_policy` to grant basic execution permissions.**\n"
                "    - This policy MUST be attached to the role created above.\n"
                "    - It MUST allow the following actions: `logs:CreateLogGroup`, `logs:CreateLogStream`, and `logs:PutLogEvents` on all log groups (`arn:aws:logs:*:*:*`). This is essential for logging.\n"
                "3.  **The `aws_lambda_function` resource itself.**\n"
                "    - The `role` attribute of the function MUST reference the ARN of the IAM role created in step 1.\n"
                "    - The `filename` attribute MUST be the exact string `'{file_name}'`.\n"
                "    - The `source_code_hash` attribute MUST use the Terraform built-in function `filebase64sha256()` with the path, like this: `filebase64sha256(\"${{path.module}}/{file_name}\")`.\n"
                "This entire chain of resources is non-negotiable for a successful Lambda deployment."
            )
            system_prompt += f"\n\n{file_context_prompt}"
            logger.debug(f"Enhanced system prompt for planner with Lambda file context.")

        # NEW Logic for S3 static website files
        if s3_file_list and user_code_path:
            logger.info(f"Planner is aware of S3 static website files: {s3_file_list}")
            
            # user_code_path is the directory containing the unzipped files.
            # The final project structure will have these files at the root.
            file_list_str = ", ".join(s3_file_list)
            
            s3_context_prompt = (
                "CRITICAL: The user wants to deploy a static website and has provided the necessary files. "
                f"The files are: [{file_list_str}].\n"
                "Your plan MUST include an `aws_s3_object` resource for EACH of these files. "
                "Follow these rules precisely:\n"
                "1. Create a separate `aws_s3_object` resource for every single file in the list.\n"
                "2. The resource name for each object should be descriptive, e.g., 's3_object_index_html', 's3_object_styles_css'.\n"
                "3. For each `aws_s3_object`, you must specify three attributes in its description: 'bucket', 'key', and 'source'.\n"
                "4. The 'bucket' attribute should reference the `aws_s3_bucket` resource you defined for the website.\n"
                "5. The 'key' attribute MUST be the filename itself (e.g., 'index.html', 'styles/main.css').\n"
                "6. The 'source' attribute MUST be a Terraform expression pointing to the local file path. Use the format `${path.module}/<filename>`, replacing `<filename>` with the actual file path from the list (e.g., `${path.module}/index.html`, `${path.module}/styles/main.css`).\n"
                "7. Do NOT create resources for directories, only for the files."
            )
            system_prompt += f"\n\n{s3_context_prompt}"
            logger.debug("Enhanced system prompt for planner with S3 website file context.")


        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                response_format={"type": "json_object"},
                temperature=0.0,
            )
            
            raw_response = response.choices[0].message.content
            logger.debug(f"📝 Raw plan from LLM: {raw_response}")

            if not raw_response:
                raise ValueError("LLM returned an empty response.")

            # Parse the JSON string and validate with Pydantic
            plan_data = json.loads(raw_response)
            plan = Plan(**plan_data)
            
            logger.info(f"✅ Plan generated and validated successfully.")
            return plan

        except json.JSONDecodeError as e:
            logger.error(f"❌ Failed to parse JSON from LLM response: {e}\nRaw response: {raw_response}")
            raise
        except ValidationError as e:
            logger.error(f"❌ Plan validation failed: {e}\nRaw response: {raw_response}")
            raise
        except Exception as e:
            logger.error(f"❌ An unexpected error occurred during plan generation: {e}", exc_info=True)
            raise 

    def generate_fix_plan(self, original_goal: str, invalid_code: str, error_message: str) -> Optional[str]:
        """
        Analyzes the invalid code and error to create a high-level fix plan.
        """
        logger.info("🤔 Planning a fix for the validation errors...")
        system_prompt = get_fix_planning_system_prompt()
        user_prompt = f"""Here is the original goal:
<goal>
{original_goal}
</goal>

Here is the invalid code that was generated:
<code>
{invalid_code}
</code>

And here is the validation error:
<error>
{error_message}
</error>

Please provide a high-level plan in JSON format to fix this.
"""
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                response_format={"type": "json_object"},
                temperature=0.0,
            )
            response_text = response.choices[0].message.content
            logger.debug(f"Raw fix plan JSON from LLM: {response_text}")
            
            plan_json = json.loads(response_text)
            fix_plan_str = plan_json.get("plan")

            if not fix_plan_str:
                logger.error("Fix plan JSON from LLM is missing the 'plan' key.")
                return None

            logger.info(f"💡 Generated Fix Plan:\n{fix_plan_str}")
            return fix_plan_str

        except json.JSONDecodeError:
            logger.error(f"Failed to decode fix plan JSON from LLM response: {response_text}")
            return None
        except Exception as e:
            logger.error(f"An unexpected error occurred during fix planning: {e}", exc_info=True)
            return None 